blank_issues_enabled: true
contact_links:
  - name: ScashX Security Policy
    url: https://github.com/scashx/scashx/blob/scashx_master/SECURITY-SCASHX.md
    about: View security policy
  - name: Satoshi Cash-X Developers
    url: https://github.com/scashx
    about: ScashX Project homepage
